name: CI Pipeline - Notification Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        working-directory: ./services/notification-service
        run: npm ci

      - name: Run API tests
        working-directory: ./services/notification-service
        run: npm test

      - name: Build Docker image
        working-directory: ./services/notification-service
        run: docker build -t chat-app-realtime-notification-service .
