version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - redis
      - mongo

  chat-service:
    build: ./services/chat-service
    container_name: chat-service
    ports:
      - "3002:3002"
    env_file:
      - ./services/chat-service/.env
    depends_on:
      - redis
      - mongo

  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    ports:
      - "3003:3003"
      - "3007:3007"  
    env_file:
      - ./services/notification-service/.env
    depends_on:
      - redis
      - mongo

  gateway-service:
    build: ./services/gateway-service
    container_name: gateway-service
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
      - chat-service
      - notification-service

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"

volumes:
  mongo-data: