version: "3.8"

services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    depends_on:
      - mongo-db  # nếu có CSDL mongo, ví dụ
  
  chat-service:
    build: ./services/chat-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002

  notification-service:
    build: ./services/notification-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003

  gateway-service:
    build: ./services/gateway-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  # Ví dụ: thêm container cho MongoDB nếu cần:
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: