version: "3.9"

services:
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo-db:27017/chatapp
      - JWT_SECRET=40bdb329c3d488d3c38a668c1da0d0163c2a3635211bffb626eb0116510e2452
    depends_on:
      - mongo-db

  chat-service:
    build: ./services/chat-service
    container_name: chat-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://mongo-db:27017/chatapp
      - JWT_SECRET=y40bdb329c3d488d3c38a668c1da0d0163c2a3635211bffb626eb0116510e2452
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo-data:
